# Generated by Django 4.0.5 on 2022-06-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_size',
            field=models.ManyToManyField(null=True, related_name='orders', through='app_api.OrderProduct', to='app_api.productsize'),
        ),
    ]
